--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JblusItsMe/CraftPermission
build-by-default: true
branches:
- main
projects:
  CraftPermission:
    path: ""
    icon: "icon.png"
...
